PORT: 25182
data_type: shard
dataloader_args:
  batch_size: 128
  drop_last: true
  num_workers: 16
  pin_memory: true
  prefetch_factor: 8
dataset_args:
  aug_prob: 0.6
  fbank_args:
    dither: 1.0
    frame_length: 25
    frame_shift: 10
    num_mel_bins: 80
  filter: true
  filter_args:
    max_num_frames: 800
    min_num_frames: 100
  num_frms: 300
  raw_wav: true
  resample_rate: 16000
  sample_num_per_epoch: 0
  shuffle: true
  shuffle_args:
    shuffle_size: 2500
  spec_aug: false
  spec_aug_args:
    max_f: 8
    max_t: 10
    num_f_mask: 1
    num_t_mask: 1
    prob: 0.6
  speed_perturb: false
enable_amp: false
exp_dir: exp/WavLM-BasePlus-FullFineTuning-MHFA-emb256-3s-LRS10-Epoch40
gpus:
- 0
- 1
- 2
- 3
log_batch_interval: 100
loss: CrossEntropyLoss
loss_args: {}
margin_scheduler: MarginScheduler
margin_update:
  epoch_iter: 2132
  final_margin: 0.2
  fix_start_epoch: 5
  increase_start_epoch: 2
  increase_type: exp
  initial_margin: 0.0
  update_margin: true
master_port: 21285
model: WavLM_Base_MHFA
model_args:
  embed_dim: 256
  head_nb: 64
  model_path: /home/jpeng/ntt/work/Data/pretrained_model/WavLM-Base+.pt
  pooling: "MHFA" #Group 
  group: 1
model_init: null
noise_data: data/musan/lmdb
num_avg: 3
num_epochs: 30
optimizer: SGD
optimizer_args:
  lr: 0.01
  momentum: 0.9
  nesterov: true
  weight_decay: 1.0e-06
projection_args:
  do_lm: false
  easy_margin: false
  embed_dim: 256
  num_class: 5994
  project_type: arc_margin_intertopk_subcenter
  scale: 32.0
reverb_data: data/rirs/lmdb
save_epoch_interval: 1
scheduler: ExponentialDecrease
scheduler_args:
  epoch_iter: 2132
  final_lr: 0.0044
  initial_lr: 0.01
  num_epochs: 30
  scale_ratio: 8.0
  warm_from_zero: true
  warm_up_epoch: 3
seed: 42
train_data: data/vox2_dev/shard.list
train_label: data/vox2_dev/utt2spk
